@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTE4OTAwOTZ9.l6GunKc20IGz5tzx-jEoumHP3Z4KsAFc-Qq-j6UY3b8


### Users Index 
GET http://localhost:3000/users

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Anita",
  "email": "anita@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "anita@test.com",
  "password": "password"
}

### Users Show
GET http://localhost:3000/users/3.json

### Users Update
PATCH http://localhost:3000/users/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "John",
  "email": "john@test.com",
  "password_digest": "password1"
}

### Users Destroy
DELETE http://localhost:3000/users/3.json


### Location_Types Index 
GET http://localhost:3000/location_types

### Location_Type Create
POST http://localhost:3000/location_types.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "Indoor Pool"
}

### Location_Type Show
GET http://localhost:3000/location_types/2.json


### Location_Type Update
PATCH http://localhost:3000/location_types/5.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "This is test"
}
### Location_Type Destroy
DELETE http://localhost:3000/location_type/.json
Authorization: Bearer {{jwt}}

### Locations Index 
GET http://localhost:3000/locations

### Locations Create
POST http://localhost:3000/locations.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "city": "test",
  "state": "test",
  "location_type_id": "1"
}

### Locations Show
GET http://localhost:3000/locations/2.json

### Locations Update
PATCH http://localhost:3000/locations/5.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "name": "test1",
  "description": "test1",
  "city": "test1",
  "state": "test1",
  "location_type_id": "2"
}

### Locations Destroy
DELETE http://localhost:3000/locations/5.json
Authorization: Bearer {{jwt}}


### Ratings Index 
GET http://localhost:3000/ratings

### Ratings Create
POST http://localhost:3000/ratings.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": "1",
  "location_id": "4",
  "rating": "5"
}

### Ratings Show
GET http://localhost:3000/ratings/1.json

### Ratings Update
PATCH http://localhost:3000/ratings/2.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": "1",
  "location_id": "4",
  "rating": "4"
}


### Ratings Destroy
DELETE http://localhost:3000/ratings/2.json
Authorization: Bearer {{jwt}}